name: PR Check
author: Mozilla-Campus-Club-of-SLIIT
description: Ensures PR compliance with project guidelines
inputs:
  token:
    description: GITHUB_TOKEN or repo scoped PAT
    required: false
    default: ${{ github.token }}
  comment-author:
    description: The account's name which the command check review should be published. Use [bot] suffix for apps.
    required: false
    default: github-actions[bot]
  pr-id:
    description: PR ID
    required: true
runs:
  using: composite
  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ inputs.pr-id }}
        comment-author: ${{ inputs.comment-author }}
        token: ${{ inputs.token }}
    
    - run: echo Bot comment ${{ steps.fc.outputs.comment-id }}
    - run: echo pull body "${{ github.event.pull_request.body }}"

    - name: Check python version
      run: python --version

    - name: Check PR
      id: check
      run: echo $(output="python ${{ github.action_path}}/index.py") >> $GITHUB_OUTPUT
      env:
        PR_DESCRIPTION: ${{ github.event.pull_request.body }}

    - run: echo "${{ steps.check.outputs.output }}"

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v5
      with:
        issue-number: 1
        comment-id: ${{ steps.fc.outputs.comment-id }}
        token: ${{ steps.app-token.outputs.bot_token }}
        body: ${{ steps.check.outputs.output }}
        edit-mode: replace
