name: PR Check
author: Mozilla-Campus-Club-of-SLIIT
description: Ensures PR compliance with project guidelines
inputs:
  token:
    description: GITHUB_TOKEN or repo scoped PAT
    required: false
    default: ${{ github.token }}
  comment-author:
    description: The account's name which the command check review should be published. Use [bot] suffix for apps.
    required: false
    default: github-actions[bot]
  check-closing-statement:
    description: Run the closing statement checker ONLY if this input is set to true
    required: false
    default: false
  check-unchecked-boxes:
    description: Check if all checkboxes are checked ONLY if this input is set to true
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: ${{ inputs.comment-author }}
        token: ${{ inputs.token }}
    
    - name: Check python version
      run: python --version
      shell: sh

    - name: Check PR
      id: check
      continue-on-error: true
      shell: sh
      run: |
        python ${{ github.action_path }}/index.py > tmp || true
        exit_code=$?
        echo "output<<EOF" >> $GITHUB_OUTPUT
        cat tmp >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
      env:
        PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        CHECK_CLOSING_STATEMENT: ${{ inputs.check-closing-statement }}
        CHECK_UNCHECKED_BOXES: ${{ inputs.check-unchecked-boxes }}

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v5
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        token: ${{ inputs.token }}
        body: ${{ steps.check.outputs.output }}
        edit-mode: replace

    - name: Report status
      run: exit ${{ steps.check.outputs.exit_code }}
      shell: sh
