name: PR Check
author: Mozilla-Campus-Club-of-SLIIT
description: Ensures PR compliance with project guidelines
inputs:
  token:
    description: GITHUB_TOKEN or repo scoped PAT
    required: false
    default: ${{ github.token }}
  comment-author:
    description: The account's name which the command check review should be published. Use [bot] suffix for apps.
    required: false
    default: github-actions[bot]
  pr-id:
    description: PR ID
    required: true
runs:
  using: composite
  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ inputs.pr-id }}
        comment-author: ${{ inputs.comment-author }}
        token: ${{ inputs.token }}
    
    - run: echo Bot comment ${{ steps.fc.outputs.comment-id }}

    - name: Check python version
      run: python --version

    - name: Check PR
      run: python index.py
      env:
        PR_DESCRIPTION: ${{ github.events.pull_request.body }}